export const STATION_CUT_REACTOR_PROFILE = Object.freeze({
    chargeTime: 0.07,
    explosionDuration: 0.95,
    chargeSizeMul: 2.4,
    flashSizeMul: 7.5,
    flashLife: 0.55,
    ringSizeMul: 9.5,
    ringLife: 0.85,
    smokeSizeMul: 6.2,
    smokeLife: 0.75,
    spikeCount: 28,
    spikeSpeedMinMul: 7.0,
    spikeSpeedMaxMul: 15.0,
    spikeSizeMinMul: 0.22,
    spikeSizeMaxMul: 0.38,
    spikeLifeMin: 0.22,
    spikeLifeMax: 0.36,
    sparkDelay: 0.06,
    sparkCount: 420,
    sparkSpeedMinMul: 4.0,
    sparkSpeedMaxMul: 9.5,
    sparkSizeMinMul: 0.05,
    sparkSizeMaxMul: 0.10,
    sparkLifeMin: 0.60,
    sparkLifeMax: 1.30,
    // bez fali z refrakcją — zostaje tylko dla rakiet supernova (2026-09-24)
    shockwave3D: null,
    heatHaze: null,
});
