export const STATION_FINAL_REACTOR_PROFILE = Object.freeze({
    chargeTime: 0.18,
    explosionDuration: 2.7,
    chargeSizeMul: 4.4,
    flashSizeMul: 15.5,
    flashLife: 1.4,
    ringSizeMul: 21.5,
    ringLife: 1.7,
    smokeSizeMul: 24.0,
    smokeLife: 2.0,
    spikeCount: 96,
    spikeSpeedMinMul: 14.0,
    spikeSpeedMaxMul: 27.0,
    spikeSizeMinMul: 0.34,
    spikeSizeMaxMul: 0.62,
    spikeLifeMin: 0.28,
    spikeLifeMax: 0.5,
    sparkDelay: 0.12,
    sparkCount: 2800,
    sparkSpeedMinMul: 5.0,
    sparkSpeedMaxMul: 13.0,
    sparkSizeMinMul: 0.07,
    sparkSizeMaxMul: 0.14,
    sparkLifeMin: 1.8,
    sparkLifeMax: 3.6,
    // bez fali z refrakcją — zostaje tylko dla rakiet supernova (2026-09-24)
    shockwave3D: null,
    heatHaze: null,
});
