export const STATION_CUT_REACTOR_PROFILE = Object.freeze({
    chargeTime: 0.07,
    explosionDuration: 0.95,
    chargeSizeMul: 2.4,
    lightDistMul: 9.0,
    lightChargeIntensity: 2.8,
    lightExplodeIntensity: 7.5,
    lightDropOff: 0.75,
    flashSizeMul: 7.5,
    flashLife: 0.55,
    ringSizeMul: 9.5,
    ringLife: 0.85,
    smokeSizeMul: 6.2,
    smokeLife: 0.75,
    spikeCount: 28,
    spikeSpeedMinMul: 7.0,
    spikeSpeedMaxMul: 15.0,
    spikeSizeMinMul: 0.22,
    spikeSizeMaxMul: 0.38,
    spikeLifeMin: 0.22,
    spikeLifeMax: 0.36,
    sparkDelay: 0.06,
    sparkCount: 420,
    sparkSpeedMinMul: 4.0,
    sparkSpeedMaxMul: 9.5,
    sparkSizeMinMul: 0.05,
    sparkSizeMaxMul: 0.10,
    sparkLifeMin: 0.60,
    sparkLifeMax: 1.30,
    shockwave3D: Object.freeze({
        scaleMul: 6.2,
        minScale: 120,
        life: 0.75,
        color: 0x55d6ff,
    }),
    heatHaze: Object.freeze({
        duration: 0.90,
        startScaleMul: 1.4,
        growthMul: 12.0,
        strength: 3.2,
    }),
});
